# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GFitStepCount' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
pod 'GoogleSignIn'
  # Pods for GFitStepCount

  target 'GFitStepCountTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GFitStepCountUITests' do
    # Pods for testing
  end

end
